export const POSTS = [
  {
    slug: "machinations-of-egregore",
    title: "Machinations of Egregore",
    excerpt: "Not a tool Claude connects to \u2014 an environment Claude operates within. Each group receives a self-contained workspace distributed through GitHub: the codebase, the command protocol, the connection layer, and the collective memory. The environment evolves as a consequence of being used.",
    date: "Feb 2026",
    tag: "Architecture",
    featured: true,
  },
  {
    slug: "context-gardening",
    title: "Context Gardening",
    excerpt: "Engineering is top-down. Gardening is bottom-up. The best context engineering is already being delegated to AI \u2014 the right move is to let it do the engineering, give it the tools, and get out of its way. What grows on a well-tended substrate is organizational intelligence that no one planted deliberately.",
    date: "Feb 2026",
    tag: "Philosophy",
    featured: true,
  },
  {
    slug: "interface-of-desire",
    title: "Interface of Desire",
    excerpt: "People create workarounds when tools don\u2019t match their natural workflow \u2014 copying conversation logs, writing \u201Chere\u2019s what I tried\u201D messages, building shared prompt libraries. These desire paths reveal latent demand. The question is whether we\u2019re amplifying something people already want to do, or asking them to adopt a foreign workflow.",
    date: "Feb 2026",
    tag: "Research",
    featured: true,
  },
  {
    slug: "emergent-governance",
    title: "Can Systems Learn How Organizations Should Work?",
    excerpt: "Most tools force organizations to pre-configure their governance. But optimal structure emerges through practice \u2014 it isn\u2019t known in advance. What happens when the system observes coordination patterns and suggests structural evolution?",
    date: "Feb 2026",
    tag: "Governance",
  },
  {
    slug: "from-retrieval-to-synthesis",
    title: "From Retrieval to Synthesis",
    excerpt: "Current AI retrieval finds documents. Synthesis is harder \u2014 insight that emerges only from seeing patterns across many contexts simultaneously. On the reflection engine that makes groups smarter than their parts.",
    date: "Feb 2026",
    tag: "Research",
  },
  {
    slug: "async-handoffs-replace-standups",
    title: "Async Handoffs Replace Standups",
    excerpt: "The standup exists for one reason: context sync. When the system holds persistent state, the ritual can evolve. How small teams eliminate sync meetings by making handoffs first-class.",
    date: "Jan 2026",
    tag: "Practice",
  },
  {
    slug: "economics-of-context",
    title: "The Economics of Organizational Memory",
    excerpt: "Why flat team pricing, what drives our costs, and how we think about building a sustainable business around context infrastructure. Not a growth experiment \u2014 a considered economics.",
    date: "Jan 2026",
    tag: "Economics",
  },
];
